name: Mirror to Radicle

# Controls when the workflow will run
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: mirror
        uses: gsaslis/mirror-to-radicle@a73e020d7f4faa8bc7993c59751667f288abcf10
        with:
          radicle-identity-alias: "${{ vars.RADICLE_IDENTITY_ALIAS }}"
          radicle-identity-passphrase: ""
          radicle-identity-private-key: "${{ secrets.RADICLE_IDENTITY_PRIVATE_KEY }}"
          radicle-identity-public-key: "${{ vars.RADICLE_IDENTITY_PUBLIC_KEY }}"
          radicle-project-name: "${{ vars.RADICLE_PROJECT_NAME }}"
          radicle-repository-id: "${{ vars.RADICLE_REPOSITORY_ID }}"
